player movement with wasd. acceleration and velocity working
Noviv/BismarkUnchained pull request #8
Opened 2019-11-14 17:34 UTC by shraymittal

2019-11-14 18:06 UTC, Noviv commented
will the controller movement be a separate PR? also this doesn't seem to allow for easy switching between the two options (like if Elmer or anyone else wants to test the other mode)

2019-11-14 18:20 UTC, shraymittal commented
We can leave this open while I add controller support. I put this here mostly if you guys wanted/needed it today. I'll have controller pushed to this PR tomorrow

2019-11-14 18:43 UTC, Noviv requested changes

2019-11-14 18:43 UTC, Noviv commented on BismarkUnchained/scenes/KinematicBody2D.gd
> +	move_and_collide(velocity)
multiply by `delta`

2019-11-14 18:43 UTC, Noviv commented on BismarkUnchained/scenes/KinematicBody2D.gd
> +var velocity
can be moved into `_process`, depending on what you're doing for controller input

2019-11-14 20:26 UTC, Noviv commented
Also, this PR needs to somehow start updating the `time_delta` global variable, so we can start working towards our core feature.

2019-11-15 22:18 UTC, Noviv approved these changes

2019-11-15 22:22 UTC, merged